const claude = '<img class="cover-mark" src="assets/claude-symbol.svg" alt="Claude">';
const dots = '<i class="dot"></i><i class="dot"></i><i class="dot"></i>';
const hand = '<svg class="hand-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M18 11V6a2 2 0 0 0-4 0v5"/><path d="M14 10V4a2 2 0 0 0-4 0v2"/><path d="M10 10.5V6a2 2 0 0 0-4 0v8"/><path d="M18 8a2 2 0 1 1 4 0v6a8 8 0 0 1-8 8h-2c-2.8 0-4.5-.86-6-2.34l-3.6-3.6a2 2 0 0 1 2.84-2.82L7 15"/></svg>';
const lucide=(paths)=>`<svg class="lucide-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${paths}</svg>`;
const constraintIcons={
  Workflow:lucide('<rect width="8" height="8" x="3" y="3" rx="2"/><path d="M7 11v4a2 2 0 0 0 2 2h4"/><rect width="8" height="8" x="13" y="13" rx="2"/>'),
  Security:lucide('<path d="M20 13c0 5-3.5 7.5-8 9-4.5-1.5-8-4-8-9V5l8-3 8 3z"/><path d="m9 12 2 2 4-4"/>'),
  Data:lucide('<ellipse cx="12" cy="5" rx="9" ry="3"/><path d="M3 5v14c0 1.7 4 3 9 3s9-1.3 9-3V5"/><path d="M3 12c0 1.7 4 3 9 3s9-1.3 9-3"/>'),
  Ownership:lucide('<circle cx="10" cy="8" r="5"/><path d="M2 21a8 8 0 0 1 13.3-6"/><path d="m16 19 2 2 4-4"/>')
};
const publishIcons={
  local:lucide('<path d="M10 4H2v16h20V6H12l-2-2z"/><path d="m8 12-2 2 2 2"/><path d="m16 12 2 2-2 2"/>'),
  publish:lucide('<path d="M12 16V4"/><path d="m7 9 5-5 5 5"/><path d="M20 15v4a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2v-4"/>'),
  url:lucide('<path d="M20 13c0 5-3.5 7.5-8 9-4.5-1.5-8-4-8-9V5l8-3 8 3z"/><path d="m9 12 2 2 4-4"/>')
};
const platformIcons={
  Routing:lucide('<circle cx="6" cy="19" r="3"/><circle cx="18" cy="5" r="3"/><path d="M6 16V8a3 3 0 0 1 3-3h6"/><path d="m15 16 3 3 3-3"/><path d="M18 8v11"/>'),
  GitHub:lucide('<path d="M15 22v-4a4.8 4.8 0 0 0-1-3.5c3.3-.4 6.8-1.6 6.8-7A5.4 5.4 0 0 0 19.4 4 5 5 0 0 0 19.3.5S18.2.1 15 1.8a13.4 13.4 0 0 0-7 0C4.8.1 3.7.5 3.7.5A5 5 0 0 0 3.6 4a5.4 5.4 0 0 0-1.4 3.7c0 5.4 3.5 6.6 6.8 7A4.8 4.8 0 0 0 8 18v4"/><path d="M8 19c-3 .9-3-1.5-4-2"/>'),
  Auth:lucide('<circle cx="12" cy="8" r="5"/><path d="M20 21a8 8 0 0 0-16 0"/><path d="m15 19 2 2 4-4"/>'),
  Secrets:lucide('<circle cx="7.5" cy="15.5" r="5.5"/><path d="m21 2-9.6 9.6"/><path d="m15.5 7.5 3 3L22 7l-3-3"/>'),
  'Deploy queue':lucide('<path d="M4 6h16"/><path d="M4 12h10"/><path d="M4 18h7"/><path d="m15 16 2 2 4-4"/>'),
  Observability:lucide('<path d="M3 3v18h18"/><path d="m7 16 4-5 4 3 5-7"/>'),
  Backups:lucide('<ellipse cx="12" cy="5" rx="8" ry="3"/><path d="M4 5v6c0 1.7 3.6 3 8 3"/><path d="M4 11v6c0 1.7 3.6 3 8 3"/><path d="M16 16h6"/><path d="m19 13 3 3-3 3"/>'),
  Kubernetes:lucide('<path d="m12 2 8.7 5v10L12 22l-8.7-5V7z"/><circle cx="12" cy="12" r="3"/><path d="M12 5v4M12 15v4M5.9 8.5l3.5 2M14.6 13.5l3.5 2M5.9 15.5l3.5-2M14.6 10.5l3.5-2"/>')
};
const slides = [
  {c:'ocean cover',o:'surface',h:`${claude}<div class="kicker step">Claude Community Amsterdam</div><h1 class="title step" style="--delay:.08s">Boiling<br>the ocean</h1><p class="subtitle step" style="--delay:.16s">How to build platforms and do what seems impossible with Claude Code</p><div class="byline step" style="--delay:.24s"><img src="assets/avatar-mw.jpg" alt="Mauricio Wolff"><div><strong>Mauricio Wolff</strong><small>12 August 2026</small></div></div>`,n:'This is the story of how I used Claude Code to build a platform that looked far too large for one person.'},
  {c:'paper',h:`<div class="two-col"><div><div class="kicker step">Hello</div><h2 class="statement small wide step" style="--delay:.08s">I’m Mauricio Wolff.</h2><p class="step" style="--delay:.16s;font-size:2rem;margin-top:1.5rem">Staff designer at Miro.<br><span class="muted">I build things.</span></p></div><img class="portrait step" style="--delay:.18s" src="assets/avatar-mw.jpg" alt="Mauricio Wolff"></div>`,n:'I’m Mauricio Wolff, a Staff Designer at Miro. I build things. Here I want to tell you how Claude Code multiplied my experience into something one person doesn’t usually ship: a whole platform.'},
  {c:'paper center',h:`<div class="kicker step">Quick show of hands</div><h2 class="statement small wide step" style="--delay:.05s">Who are you?</h2><div class="roles"><div class="role step" style="--delay:.12s"><div class="role-icon">${hand}</div><strong>Designer?</strong></div><div class="role step" style="--delay:.2s"><div class="role-icon">${hand}</div><strong>PM?</strong></div><div class="role step" style="--delay:.28s"><div class="role-icon">${hand}</div><strong>Engineer?</strong></div></div><p class="hand-question step" style="--delay:.36s">${hand}<span>Who has built with AI?</span></p>`,n:'If you’ve used AI tools to build beyond your own role, this story is for you.'},
  {c:'paper center',h:`<div class="dictionary step"><div class="dictionary-head"><strong>Boil the ocean</strong><span>idiom</span></div><div class="pronunciation">/bɔɪl ði ˈoʊʃən/</div><div class="definition">To undertake a project whose scope is so vast that completing it would be <em>impractical</em>, regardless of available people or resources.</div></div>`,n:'“Boiling the ocean” is usually a useful warning that a project is too large to attempt. This talk explores what happened when I ignored it, and which practices kept ambition from turning into chaos.'},
  {c:'dark center',h:`<div class="section-num step">Chapter one</div><div class="section-title step" style="--delay:.08s;font-size:clamp(6rem,15vw,12.5rem);letter-spacing:-.025em">The story</div>`,n:'To explain what this means, I’ll tell you a story about what happened at Miro.'},
  {c:'paper center middle',h:`<div class="tool-journey"><div class="tool-logo step"><img src="assets/lovable-logo.svg" alt="Lovable"><span>Lovable</span></div><div class="tool-logo step" style="--delay:.1s"><img src="assets/replit-logo.svg" alt="Replit"><span>Replit</span></div><div class="journey-arrow" style="opacity:0" aria-hidden="true">→</div><div class="tool-logo claude-code" style="opacity:0" aria-hidden="true"><img src="assets/claude-symbol.svg" alt=""><span>Claude Code</span></div></div><h2 class="statement small wide" style="margin-top:4rem;visibility:hidden" aria-hidden="true">Then things<br>took off.</h2>`,n:'At Miro, around one year ago, designers started to prototype with AI tools like Lovable and Replit.'},
  {c:'paper center middle',h:`<div class="tool-journey"><div class="tool-logo"><img src="assets/lovable-logo.svg" alt="Lovable"><span>Lovable</span></div><div class="tool-logo"><img src="assets/replit-logo.svg" alt="Replit"><span>Replit</span></div><div class="journey-arrow step" style="--delay:.1s">→</div><div class="tool-logo claude-code step" style="--delay:.25s"><img src="assets/claude-symbol.svg" alt="Claude"><span>Claude Code</span></div></div><h2 class="statement small wide step" style="--delay:1.25s;margin-top:4rem">Then things<br><span class="accent">took off.</span></h2>`,n:'Then we got access to Claude Code. Being able to use powerful models on your own machine and prototype locally was a game changer, and things took off.'},
  {c:'paper center middle',h:`<div class="browser localhost-browser step"><div class="window-bar">${dots}<div class="url">localhost:3000</div></div><div class="browser-body"><strong>It works!</strong><canvas class="confetti-canvas" aria-hidden="true"></canvas></div></div>`,n:'Everybody remembers the first time they opened localhost on their own machine... Feels magical. It’s like having the whole internet on your computer!'},
  {c:'image-slide',h:`<img class="fullscreen-image" src="assets/share-localhost-clean.png" alt="Boromir"><div class="impact-text impact-top">ONE DOES NOT SIMPLY</div><div class="impact-text impact-bottom">SHARE LOCALHOST</div>`,n:'But other people cannot use that URL. I’ve seen it a few times: someone shares on Slack "hey, check this awesome thing I did http://localhost:3000"... 🤦‍♂️'},
  {c:'paper center',h:`<div class="kicker step">Plenty of options</div><h2 class="statement small wide step" style="--delay:.06s">Many ways to deploy.<br><span class="muted">Built for different needs.</span></h2><div class="deployment-logos">${[['lovable-logo.svg','Lovable'],['replit-logo.svg','Replit'],['vercel-logo.svg','Vercel'],['netlify-logo.svg','Netlify'],['railway-logo.svg','Railway'],['flyio-logo.svg','Fly.io'],['cloudflare-logo.svg','Cloudflare']].map((x,i)=>`<div class="deployment-logo step" style="--delay:${.1+i*.055}s"><img src="assets/${x[0]}" alt="${x[1]}"><span>${x[1]}</span></div>`).join('')}</div>`,n:'There are many solutions for sharing apps or prototypes. They are good tools, but they were designed around different needs and constraints than ours.'},
  {c:'paper center',h:`<div class="kicker step">Our constraints</div><h2 class="statement small wide step" style="max-width:none">Deployment existed.<br><span class="accent" style="font-size:.8em;white-space:nowrap">The experience we wanted didn’t.</span></h2><div class="constraint-grid">${['Workflow','Security','Data','Ownership'].map((x,i)=>`<div class="constraint step" style="--delay:${.12+i*.08}s">${constraintIcons[x]}<b>${x}</b></div>`).join('')}</div>`,n:'We needed a simple workflow for non-engineers, approved infrastructure, secure credentials, governed data, and clear ownership. Existing options solved parts of this, but not the complete experience we wanted.'},
  {c:'dark center middle',h:`<div class="publish-steps"><div class="publish-step claude-local step" style="--delay:.1s"><img src="assets/claude-symbol.svg" alt="Claude"><b>Create locally</b></div><div class="publish-arrow step" style="--delay:.45s">→</div><div class="publish-step green step" style="--delay:.65s">${publishIcons.publish}<b>Publish</b></div><div class="publish-arrow step" style="--delay:1s">→</div><div class="publish-step slack-share step" style="--delay:1.2s"><img src="assets/slack-logo.svg" alt="Slack"><b>Share secure URL</b></div></div><h2 class="statement small wide step" style="--delay:1.55s;margin-top:4rem">Create locally.<br><span class="success">Share in seconds.</span></h2>`,n:'The goal was simple: create something on your computer, publish it in seconds, and receive a secure URL anyone at Miro could open. No deployment expertise, no config, and no new vendor account.'},
  {c:'dark nopad',h:`<div class="screenshot step"><video class="demo-video" src="assets/zero-to-vibelab-min.mp4" data-autoplay muted playsinline controls></video><div class="demo-badge">215 seconds</div></div>`,n:'In this demo, an app is generated and runs on localhost, then published through our platform, Vibelab, and opened at a secure company URL.'},
  {c:'paper center middle',h:`<h2 class="statement wide step">Simple experience.</h2><h2 class="statement wide danger step" style="--delay:.35s;margin-top:2.5rem">Platform-size problem.</h2>`,n:'Making publishing feel simple required hiding substantial platform complexity.'},
  {c:'ocean center',o:'deep',h:`<div class="kicker honeycomb-title step">Behind the simple experience</div><div class="honeycomb step" style="--delay:.1s"><div class="hex core"><span class="hex-content"><img class="platform-logo" src="assets/platform-logo.png?v=2" alt="Platform"><b>Platform</b></span></div>${['Routing','GitHub','Auth','Secrets','Deploy queue','Observability','Backups','Kubernetes'].map((x,i)=>`<div class="hex hex-${i+1}"><span class="hex-content">${platformIcons[x]}<b>${x}</b></span></div>`).join('')}</div>`,n:'Behind the simple experience sit Kubernetes, dynamic routing, GitHub integration, authentication, secrets, deployment queues, framework detection, observability, database recovery, and CI/CD. All of it needs to be fast and transparent for the user.'},
  {c:'ocean center',o:'deep',h:`<h2 class="statement wide step">That was<br><span style="color:var(--aqua)">the ocean.</span></h2>`,n:'This platform was my ocean: a useful product whose implementation seemed far beyond reason.'},
  {c:'dark center middle',h:`<div class="est-glow" style="--glow:199,91,76" aria-hidden="true"></div><div class="kicker step" style="color:var(--red);margin-bottom:3rem">Conventional estimate</div><div class="estimate-stack step" style="--delay:.08s"><div class="estimate-numbers danger"><span>5</span><small>to</small><span>6</span></div><div class="estimate-label"><strong>engineers</strong><span>9 to 12 months</span></div><div class="eng-row">${Array.from({length:6},(_,i)=>`<span class="eng step" style="--delay:${.35+i*.09}s">${lucide('<circle cx="12" cy="8" r="5"/><path d="M20 21a8 8 0 0 0-16 0"/>')}</span>`).join('')}</div></div>`,n:'A conservative estimate for building what we wanted in production is five to six experienced engineers working for nine to twelve months. This is an informed estimate, not a measured counterfactual. In any case, unfeasible.'},
  {c:'dark center middle',h:`<div class="est-glow" style="--glow:141,184,154" aria-hidden="true"></div><div class="kicker step" style="color:var(--green);margin-bottom:3rem">What actually happened</div><div class="estimate-stack step" style="--delay:.08s"><div class="estimate-numbers" style="color:var(--green)"><span>3</span></div><div class="estimate-label"><strong>weeks</strong><span>to MVP</span></div></div><div class="team-row"><div class="team-member step" style="--delay:.35s"><img src="assets/avatar-mw.jpg" alt="Mauricio Wolff"><b>1 design engineer</b></div><span class="team-plus step" style="--delay:.5s">+</span><div class="team-member step" style="--delay:.65s"><img class="claude" src="assets/claude-symbol.svg" alt="Claude Code"><b>Claude Code</b></div><span class="team-plus step" style="--delay:.8s">+</span><div class="team-member step" style="--delay:.95s"><img src="assets/avatar-sre.png" alt="SRE"><b>support from one SRE</b></div></div>`,n:'But in reality, I released the MVP in three weeks with a team of one design engineer (myself) + Claude Code + one SRE supporting. The broader product followed in about two months. Six months in, we have more than 600 apps deployed and around 1400 deployments per week.'},
  {c:'dark center',o:null,h:`<div class="section-num step">Chapter two</div><div class="section-title step" style="--delay:.08s">How</div>`,n:'Building ambitious software with agents starts with how the work is framed, planned, and remembered.'},
  {c:'paper center middle',h:`<div class="warn-icon step">${lucide('<path d="m21.73 18-8-14a2 2 0 0 0-3.48 0l-8 14A2 2 0 0 0 4 20h16a2 2 0 0 0 1.73-2Z"/><path d="M12 9v4"/><path d="M12 17h.01"/>')}</div><div class="kicker step" style="--delay:.06s">Disclaimer</div><h2 class="statement wide step" style="--delay:.12s;line-height:1.2">Not a recipe.<br><span class="muted">What worked for me.</span></h2>`,n:'This is not a universal recipe. It is an account of practices that worked for me, offered so you can adapt the useful parts to your own constraints.'},
  {c:'paper center middle',h:`<div class="kicker slide-tag step">1. The idea</div><div class="warn-icon step" style="--delay:.08s">${lucide('<path d="M15 14c.2-1 .7-1.7 1.5-2.5 1-.9 1.5-2.2 1.5-3.5A6 6 0 0 0 6 8c0 1 .2 2.2 1.5 3.5.7.7 1.3 1.5 1.5 2.5"/><path d="M9 18h6"/><path d="M10 22h4"/>')}</div><h2 class="statement wide step" style="--delay:.15s">The idea comes<br><span style="color:#e0aa4e">from you.</span></h2>`,n:'Claude can refine and challenge an idea, but a human must first decide what matters, which problem deserves solving, and what experience the product should create. In this case, it was a novel way to deploy web apps faster than any other method.'},
  {c:'dark center middle',h:`<div class="kicker slide-tag step">2. Edit your global CLAUDE.md</div><div class="mdoc-row"><div class="mdoc mdoc-small step" style="--delay:.1s"><div class="mdoc-name">CLAUDE.md</div><div class="mdoc-body"><span style="color:var(--blue)">@AGENTS.md</span></div></div><div class="mdoc step" style="--delay:.25s"><div class="mdoc-name">AGENTS.md</div><div class="mdoc-body"><span class="mh"># Planning rules</span>- Challenge my assumptions.
- Do not code yet.
- One change at a time.
- Explain the why, not just what, in terse form.
- Never speculate about code you haven't read.
- Prefer editing files over creating new ones.
- Check in before major changes.</div></div></div>`,n:'Claude Code likes to write code ASAP. I counter it with simple planning instructions that apply to any project, at user level. I keep them in AGENTS.md to stay compatible with other harnesses.'},
  {c:'paper center',h:`<div class="kicker slide-tag step">3. Working ratio</div><h2 class="statement small wide step">Plan more.<br><span class="muted">Fix less.</span></h2><div class="ratio" style="margin-top:4.5rem;gap:1.8rem"><div class="ratio-row"><b>70% plan</b><div class="bar"><div class="fill" style="--w:70%;--delay:.12s"></div></div></div><div class="ratio-row"><b>20% tinker</b><div class="bar"><div class="fill" style="--w:20%;--delay:.22s"></div></div></div><div class="ratio-row"><b>10% fix</b><div class="bar"><div class="fill" style="--w:10%;--delay:.32s"></div></div></div></div>`,n:'My rough working split is seventy percent planning, twenty percent tinkering (iterating, improving, tweaking), and ten percent fixing. The more you plan, the less you fix. Because I’m a designer, tinkering is almost mandatory.'},
  {c:'paper center',h:`<div class="kicker slide-tag step">4. Spec it out</div><h2 class="statement small wide step">Three documents.</h2><div class="mdoc-files">${[['PITCH.md',[['# Why',[88]],['# What',[72]],['# Definition of done',[81]]]],['EXPERIENCE.md',[['# Feel',[85,62]],['# Principles',[78,90]]]],['ARCHITECTURE.md',[['# Tech stack',[76]],['# Infra and security',[84]],['# Unknowns',[70]]]]].map((f,i)=>`<div class="mdoc step" style="--delay:${.12+i*.12}s"><div class="mdoc-name">${f[0]}</div><div class="mdoc-body">${f[1].map(s=>`<span class="mh">${s[0]}</span>${s[1].map(w=>`<i class="scribble" style="width:${w}%"></i>`).join('')}`).join('')}</div></div>`).join('')}</div>`,n:'I begin with three small documents. Pitch defines why, what, and done. Experience defines how the product should feel. Architecture tests feasibility and exposes what I still need to learn. They need to be super short, so I can pull them into context whenever I need.'},
  {c:'dark center middle',h:`<div class="kicker slide-tag step">5. Plan every change</div><div class="mdoc plan-doc step"><div class="mdoc-name">.plans/dashboard-templates-by-branch-count.md</div><div class="mdoc-body"><span class="mh"># Order templates by branch count</span><i class="scribble" style="width:82%"></i><span class="mh mh2">## Current behavior</span><i class="scribble" style="width:90%"></i><i class="scribble" style="width:68%"></i><span class="mh mh2">## Change</span><i class="scribble" style="width:74%"></i><div class="code-scribble"><i style="width:46%"></i><i style="width:64%"></i><i style="width:38%"></i></div><span class="mh mh2">## Files</span><i class="scribble" style="width:52%"></i></div></div><h2 class="statement small wide step" style="--delay:.2s;margin-top:2.8rem"><span style="color:var(--orange)">1 change</span> = 1 plan</h2>`,n:'Every feature or meaningful change gets its own small Markdown plan in .plans, versioned with the code. This one is a real plan from the platform: current behavior, the change, and the files it touches. Old plans are committed in .archives.'},
  {c:'paper center',h:`<div class="kicker slide-tag step">6. Protect focus</div><h2 class="statement small wide step" style="line-height:1.15">New idea?<br><span class="accent">Index it.</span></h2><div class="plan-queue" style="margin-top:3.5rem"><div class="mdoc step" style="--delay:.1s"><div class="mdoc-name">.plans/current-change.md</div><div class="mdoc-body"><span class="mh"># Current plan</span><i class="scribble" style="width:86%"></i><i class="scribble" style="width:64%"></i><i class="scribble" style="width:75%"></i></div></div><div class="idea-card">${lucide('<path d="M15 14c.2-1 .7-1.7 1.5-2.5 1-.9 1.5-2.2 1.5-3.5A6 6 0 0 0 6 8c0 1 .2 2.2 1.5 3.5.7.7 1.3 1.5 1.5 2.5"/><path d="M9 18h6"/><path d="M10 22h4"/>')}</div><div class="mdoc step" style="--delay:1.3s"><div class="mdoc-name">.plans/INDEX.md</div><div class="mdoc-body"><span class="mh"># Queue</span><div class="queue-row">- [ ] share links</div><div class="queue-row">- [ ] usage stats</div><div class="queue-row">- [ ] dark mode</div></div></div></div>`,n:'When a new idea appears during execution, I create a one-line plan, add it to the index for later, and continue with the current one. This is also committed, so the idea survives without expanding the current scope.'},
  {c:'paper center',h:`<div class="kicker slide-tag step">7. Split your context</div><h2 class="statement small wide step" style="line-height:1.15">Right context.<br><span class="muted">Right moment.</span></h2><div class="layer-grid">${[['TRUTH','/AGENTS.md','<path d="M15 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V7z"/><path d="M14 2v4a2 2 0 0 0 2 2h4"/><path d="M10 9H8"/><path d="M16 13H8"/><path d="M16 17H8"/>'],['INTENT','<span style="opacity:.7">/.plans</span>','<circle cx="12" cy="12" r="10"/><circle cx="12" cy="12" r="6"/><circle cx="12" cy="12" r="2"/>'],['LEARNING','memory','<path d="M21.42 10.92a1 1 0 0 0 0-1.84l-8.58-3.91a2 2 0 0 0-1.66 0L2.6 9.08a1 1 0 0 0 0 1.83l8.58 3.91a2 2 0 0 0 1.66 0z"/><path d="M22 10v6"/><path d="M6 12.5V16a6 3 0 0 0 12 0v-3.5"/>'],['HISTORY','<span style="opacity:.7">/.archives</span>','<rect width="20" height="5" x="2" y="3" rx="1"/><path d="M4 8v11a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8"/><path d="M10 12h4"/>']].map((x,i)=>`<div class="layer-card step" style="--delay:${.12+i*.09}s">${lucide(x[2])}<b>${x[0]}</b><span>${x[1]}</span></div>`).join('')}</div>`,n:'AGENTS.md stores current architecture, commands, constraints, and invariants. Plans are the immediate things to do. Memory comes from the harness and stores focused lessons. Archives preserve completed plans and historical decisions.'},
  {c:'dark center middle',h:`<div class="kicker slide-tag step">8. Check your context size</div><div class="gauge step" style="--delay:.1s"><div class="gauge-value">45%</div></div><h2 class="statement small wide step" style="--delay:.22s;margin-top:3rem">Keep context fresh.</h2><p class="step" style="--delay:.34s;margin-top:1.8rem;font-size:1.7rem;color:rgba(240,238,230,.6)">Hand over with <a href="https://github.com/bitbonsai/wrap" target="_blank" rel="noopener" style="font-family:var(--mono);font-size:1.5rem;color:var(--orange-soft);background:rgba(255,255,255,.08);padding:.25rem .8rem;border-radius:.5rem;text-decoration:none">/wrap</a> or your own handover technique.</p>`,n:'I try to keep active context below roughly 40 to 50 percent. This avoids the dumb zone, regardless of context size. When context grows noisy, I preserve a handover with a skill like https://github.com/bitbonsai/wrap, clear the session, and restart.'},
  {c:'paper center',h:`<div class="kicker slide-tag step">9. Agent teams / workflows</div><h2 class="statement small wide step">Plan the agent team first.</h2><div class="org"><div class="org-lead step" style="--delay:.15s"><img src="assets/claude-symbol.svg" alt=""><div><b>Lead agent</b><span>splits work · maps dependencies · defines proof</span></div></div><div class="org-stem"></div><div class="org-tasks">${[['auth routes',[['model','opus/<em class="eff-high">high</em>'],['deps','schema'],['verify','bun test']]],['deploy queue',[['model','sonnet/<em class="eff-med">medium</em>'],['deps','auth'],['verify','typecheck']]],['dashboard ui',[['model','sonnet/<em class="eff-low">low</em>'],['deps','api'],['verify','screenshot']]]].map((t,i)=>`<div class="org-task step" style="--delay:${.55+i*.15}s"><div class="org-task-head"><img src="assets/claude-symbol.svg" alt=""><b>${t[0]}</b></div><div class="spec">${t[1].map(r=>`<div class="spec-row"><span>${r[0]}</span><b>${r[1]}</b></div>`).join('')}</div></div>`).join('')}</div></div>`,n:'For larger changes, I ask the most capable model to act as the lead. It divides the goal into tasks, maps dependencies, chooses a model and effort for each task, and defines how the results will be verified.'},
  {c:'ocean nopad',o:'current',h:`<div class="screenshot step"><img class="agents-shot" src="assets/agents-tmux.png" alt="Terminal with fourteen Claude Code agents running in parallel"></div>`,n:'I once ran fourteen agents in parallel. I’ve been working with Agent Teams since it was experimental in Claude, and until recently that was how I delivered this product.'},
  {c:'dark center middle',h:`<div class="mdoc code-doc step"><div class="mdoc-name">workflow.ts</div><pre class="mdoc-code"><span class="k">export const</span> meta = { name: <span class="s">'ship-dashboard'</span>, phases: [<span class="s">'Build'</span>, <span class="s">'Verify'</span>] }

<span class="f">phase</span>(<span class="s">'Build'</span>)
<span class="k">const</span> api = <span class="k">await</span> <span class="f">agent</span>(<span class="s">'Build auth routes'</span>, { model: <span class="s">'opus'</span>, effort: <span class="s">'high'</span> })
<span class="k">const</span> ui  = <span class="k">await</span> <span class="f">agent</span>(<span class="s">'Build dashboard ui'</span>, { model: <span class="s">'sonnet'</span>, effort: <span class="s">'low'</span>, dependsOn: [api] })

<span class="f">phase</span>(<span class="s">'Verify'</span>)
<span class="k">await</span> <span class="f">agent</span>(<span class="s">'Review the diff. Refute if broken.'</span>, { verify: <span class="s">'bun test'</span> })</pre></div><h2 class="statement small wide step" style="--delay:.25s;margin-top:2.5rem">Inspect before running.</h2>`,n:'But now Claude Code has multi-agent workflows: a TypeScript file where you can read and edit the tasks, models, effort, and dependencies in a deterministic way.'},
  {c:'paper center',h:`<div class="kicker step">The method</div><h2 class="statement small wide step">Recap.</h2><div class="method-cols"><div class="mcol"><div class="mcol-head step" style="--delay:0.10s">Start</div><div class="mcol-items"><div class="mstep step" style="--delay:0.15s"><b>1</b><span>The idea</span></div><div class="mstep step" style="--delay:0.23s"><b>2</b><span>Global CLAUDE.md</span></div><div class="mstep step" style="--delay:0.31s"><b>3</b><span>Working ratio</span></div></div></div><div class="mcol"><div class="mcol-head step" style="--delay:0.34s">Plan</div><div class="mcol-items"><div class="mstep step" style="--delay:0.39s"><b>4</b><span>Spec it out</span></div><div class="mstep step" style="--delay:0.47s"><b>5</b><span>Plan every change</span></div><div class="mstep step" style="--delay:0.55s"><b>6</b><span>Protect focus</span></div></div></div><div class="mcol"><div class="mcol-head step" style="--delay:0.58s">Scale</div><div class="mcol-items"><div class="mstep step" style="--delay:0.63s"><b>7</b><span>Split your context</span></div><div class="mstep step" style="--delay:0.71s"><b>8</b><span>Check your context size</span></div><div class="mstep step" style="--delay:0.79s"><b>9</b><span>Agent teams / workflows</span></div></div></div></div>`,n:'Nine practices carry the method: own the idea, keep durable instructions, plan more than you fix, spec before building, plan every change, index new ideas, layer your context, keep it fresh, and plan agent teams/workflows before running them.'},
  {c:'dark center',h:`<div class="section-num step">Chapter three</div><div class="section-title step" style="--delay:.08s">Learnings</div>`,n:'Every ambitious build teaches lessons the hard way. These are mine.'},  {c:'dark center middle',h:`<div class="est-glow" style="--glow:199,91,76;left:31%;top:52%" aria-hidden="true"></div><div class="kicker step" style="color:var(--red);margin-bottom:3rem">Moving too fast</div><div class="revert-wrap"><div class="estimate-stack step" style="--delay:.08s"><div class="estimate-numbers danger"><span>30</span></div><div class="estimate-label"><strong>commits</strong><span>reverted</span></div></div><div class="gitlog step" style="--delay:.5s"><div class="gitrow" style="--delay:0.65s"><span class="sha">a3f2c1e</span> revert: runner cleanup</div><div class="gitrow" style="--delay:0.83s"><span class="sha">9b7d44a</span> revert: queue refactor</div><div class="gitrow" style="--delay:1.01s"><span class="sha">c1e8f02</span> revert: auth middleware</div><div class="gitrow" style="--delay:1.19s"><span class="sha">5d2a9bc</span> revert: deploy hooks</div><div class="gitrow" style="--delay:1.37s"><span class="sha">e774f13</span> revert: router rewrite</div><div class="gitrow" style="--delay:1.55s"><span class="sha">b0c6d58</span> revert: cache layer</div><div class="gitrow" style="--delay:1.75s;color:rgba(240,238,230,.4)">… 24 more</div></div></div>`,n:'At one point I accepted Claude’s suggestions without fully understanding them. Each change looked reasonable on its own. Confusion compounded until I had to revert thirty commits. Make sure you know what the system does at all times.'},
  {c:'dark center middle',h:`<div class="est-glow" style="--glow:199,91,76" aria-hidden="true"></div><div class="warn-icon step" style="color:var(--red)">${lucide('<path d="M2.586 16.726A2 2 0 0 1 2 15.312V8.688a2 2 0 0 1 .586-1.414l4.688-4.688A2 2 0 0 1 8.688 2h6.624a2 2 0 0 1 1.414.586l4.688 4.688A2 2 0 0 1 22 8.688v6.624a2 2 0 0 1-.586 1.414l-4.688 4.688a2 2 0 0 1-1.414.586H8.688a2 2 0 0 1-1.414-.586z"/><path d="M8 12h8"/>')}</div><h2 class="statement wide step" style="--delay:.12s;line-height:1.12">Never merge faster<br><span style="color:var(--red)">than you understand.</span></h2>`,n:'I skim every diff and inspect architecture, security, data, and unfamiliar code more deeply. If I cannot explain what changed and why, I ask Claude to explain it and simplify it until I understand what’s in the system.'},
  {c:'dark center middle',h:`<div class="mdoc step" style="width:min(56rem,94%)"><div class="mdoc-name">AGENTS.md</div><div class="mdoc-body"><span class="mh"># Invariants — do not remove</span>- Old runner serves until the new one is healthy.
- Apps never bind public ports; the proxy routes.
- Secrets stay in the vault, never in code.</div></div><h2 class="statement small wide step" style="--delay:.2s;margin-top:2.8rem">Write down what<br><span style="color:var(--orange)">must stay true.</span></h2>`,n:'Some conditions must remain true. Write these critical invariants down with their reasons. A written rule stops a sensible-looking cleanup from causing downtime.'},
  {c:'dark center middle',h:`<div class="fire-flow"><div class="fire-step step" style="--delay:0.10s;color:var(--red)"><svg class="lucide-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="m8 2 1.88 1.88"/><path d="M14.12 3.88 16 2"/><path d="M9 7.13v-1a3.003 3.003 0 1 1 6 0v1"/><path d="M12 20c-3.3 0-6-2.7-6-6v-3a4 4 0 0 1 4-4h4a4 4 0 0 1 4 4v3c0 3.3-2.7 6-6 6"/><path d="M12 20v-9"/><path d="M6.53 9C4.6 8.8 3 7.1 3 5"/><path d="M6 13H2"/><path d="M3 21c0-2.1 1.7-3.9 3.8-4"/><path d="M20.97 5c0 2.1-1.6 3.8-3.5 4"/><path d="M22 13h-4"/><path d="M17.2 17c2.1.1 3.8 1.9 3.8 4"/></svg><b>BUG</b></div><div class="fire-arrow step" style="--delay:0.20s">→</div><div class="fire-step step" style="--delay:0.32s;color:rgba(240,238,230,.85)"><svg class="lucide-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M14.7 6.3a1 1 0 0 0 0 1.4l1.6 1.6a1 1 0 0 0 1.4 0l3.77-3.77a6 6 0 0 1-7.94 7.94l-6.91 6.91a2.12 2.12 0 0 1-3-3l6.91-6.91a6 6 0 0 1 7.94-7.94l-3.76 3.76z"/></svg><b>FIX</b></div><div class="fire-arrow step" style="--delay:0.42s">→</div><div class="fire-step step" style="--delay:0.54s;color:var(--green)"><svg class="lucide-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><circle cx="12" cy="12" r="10"/><path d="m9 12 2 2 4-4"/></svg><b>TEST</b></div><div class="fire-arrow step" style="--delay:0.64s">→</div><div class="fire-step step" style="--delay:0.76s;color:var(--orange)"><svg class="lucide-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M15 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V7z"/><path d="M14 2v4a2 2 0 0 0 2 2h4"/><path d="M10 9H8"/><path d="M16 13H8"/><path d="M16 17H8"/></svg><b>RULE</b></div></div><h2 class="statement small wide step" style="--delay:1s;margin-top:4rem">Incidents become <span style="color:var(--orange)">memory.</span></h2>`,n:'Incidents will happen, and you will jump in to put out fires. Each fire should leave behind a code fix, a test, and a written rule, so the next session begins with the lesson already learned.'},
  {c:'paper center middle',h:`<div class="skill-flow"><div class="prompt-stack"><div class="mini-doc step" style="--delay:0.10s"><b>prompt</b><i class="scribble" style="width:88%"></i><i class="scribble" style="width:60%"></i></div><div class="mini-doc step" style="--delay:0.20s"><b>prompt</b><i class="scribble" style="width:74%"></i><i class="scribble" style="width:82%"></i></div><div class="mini-doc step" style="--delay:0.30s"><b>prompt</b><i class="scribble" style="width:90%"></i><i class="scribble" style="width:52%"></i></div></div><div class="flow-arrow step" style="--delay:.45s">→</div><div class="mdoc skill-doc step" style="--delay:.6s"><div class="mdoc-name">SKILL.md</div><div class="mdoc-body"><span class="mh"># Context</span><i class="scribble" style="width:84%"></i><span class="mh"># Steps</span><i class="scribble" style="width:70%"></i><i class="scribble" style="width:78%"></i><span class="mh"># Checks</span><i class="scribble" style="width:56%"></i></div></div></div><h2 class="statement small wide step" style="--delay:.8s;margin-top:3.5rem;line-height:1.15">Explained twice?<br><span class="accent">Make a project skill.</span></h2>`,n:'When you catch yourself doing the same thing twice, consider turning it into a project skill. Skills can live inside the project folder, so they travel with the repo and everyone picks them up.'},
  {c:'paper',h:`<div class="two-col"><div><div class="kicker step">Release early</div><h2 class="statement small step" style="--delay:.08s;line-height:1.2;font-size:3.9rem;max-width:none;white-space:nowrap"><span class="muted">Tests = silver.</span><br>Feedback = <span style="color:#d99b26">gold.</span></h2></div><div class="feedback step" style="--delay:.2s"><div class="feedback-track"><div class="sticky" style="font-size:1.25rem">I got stuck here.</div><div class="sticky" style="font-size:1.25rem">Can this also…?</div><div class="sticky" style="font-size:1.05rem">This saved me two hours.</div><div class="sticky" style="font-size:1.5rem">What if…?</div><div class="sticky" style="font-size:1.25rem">I love this.</div><div class="sticky" style="font-size:1.25rem">I showed my team.</div><div class="sticky" style="font-size:1.05rem">Shipped in one minute.</div><div class="sticky" style="font-size:1.05rem">Where do I report bugs?</div><div class="sticky" style="font-size:1.05rem">Exactly what we needed.</div><div class="sticky" style="font-size:1.05rem">Can my team use it too?</div><div class="sticky" style="font-size:1.25rem">I got stuck here.</div><div class="sticky" style="font-size:1.25rem">Can this also…?</div><div class="sticky" style="font-size:1.05rem">This saved me two hours.</div><div class="sticky" style="font-size:1.5rem">What if…?</div><div class="sticky" style="font-size:1.25rem">I love this.</div><div class="sticky" style="font-size:1.25rem">I showed my team.</div><div class="sticky" style="font-size:1.05rem">Shipped in one minute.</div><div class="sticky" style="font-size:1.05rem">Where do I report bugs?</div><div class="sticky" style="font-size:1.05rem">Exactly what we needed.</div><div class="sticky" style="font-size:1.05rem">Can my team use it too?</div></div></div></div>`,n:'Tests show that software works; a product succeeds only when it’s useful to people. Release early and listen closely: first users will reveal what’s missing. Fix and improve fast.'},
  {c:'dark center middle',h:`<div class="adopt"><span class="adopt-easy step">Easy</span><span class="adopt-conv step" style="--delay:.5s">Convenient</span><span class="adopt-fun">Fun</span></div><canvas class="confetti-canvas" aria-hidden="true"></canvas>`,n:'And remember: your products should be easy, offer a more convenient way to achieve something, and if possible, be FUN.'},
  {c:'ocean center',o:'raft',h:`<h2 class="statement wide step">Oceans didn’t<br><span style="color:var(--aqua)">get smaller.</span></h2><p class="step" style="--delay:.35s;font-size:2rem;margin-top:2rem;color:rgba(240,238,230,.75)">But now you’ve got a raft to cross through it.</p>`,n:'Claude Code did not reduce the platform’s scope or remove its complexity. What changed is the way I worked: planning, durable context, and verification formed a raft that made it possible to cross that ocean. "Boil" was a bit of a dramatic effect, but I hope you get the point.'},
  {c:'dark center',h:`${claude}<h2 class="statement step">Thank you!</h2><div class="resources step" style="--delay:.18s"><a href="https://mauriciowolff.com" target="_blank" rel="noopener" class="qr" aria-label="QR code to mauriciowolff.com"><img src="assets/qr-mw.svg" alt="QR code linking to mauriciowolff.com"></a><div class="resource-copy"><strong>Mauricio Wolff</strong><br>@bitbonsai</div></div>`,n:'Thank you for following this story. If you wanna know more, find me at https://mauriciowolff.com'}
];

const root = document.getElementById('slides');
root.innerHTML = slides.map((s,i)=>`<section class="${s.c||''}" data-caption="${i}" ${s.o?`data-ocean="${s.o}"`:''}>${s.h}</section>`).join('');

Reveal.initialize({
  hash:true,width:1400,height:788,margin:0,minScale:.2,maxScale:2,
  transition:'none',controls:true,progress:true,
  center:false,slideNumber:false
});

const captionBox=document.getElementById('captions');
const captionText=captionBox.querySelector('span');
const toggle=document.getElementById('captions-toggle');
const number=document.getElementById('slide-number');
let captionsVisible=true;
captionBox.classList.toggle('hidden',!captionsVisible);
toggle.setAttribute('aria-pressed',String(captionsVisible));

let confettiFrame,confettiTimer;
function stopConfetti(){
  clearTimeout(confettiTimer);
  cancelAnimationFrame(confettiFrame);
  confettiFrame=confettiTimer=null;
}
function startConfetti(slide){
  const canvas=slide?.querySelector('.confetti-canvas');
  if(!canvas)return;
  confettiTimer=setTimeout(()=>{
    const ctx=canvas.getContext('2d');
    const dpr=Math.min(devicePixelRatio,2),rect=canvas.getBoundingClientRect();
    canvas.width=rect.width*dpr;canvas.height=rect.height*dpr;ctx.scale(dpr,dpr);
    const colors=['#d97757','#f4c95d','#4b73ff','#ff7eb0','#56c596','#9b6cff'];
    const burst=canvas.dataset.burst?.split(',').map(Number);
    const pieces=Array.from({length:363},()=>{
      const base={size:4+Math.random()*8,phase:Math.random()*Math.PI*2,
        rotation:Math.random()*Math.PI*2,spin:-7+Math.random()*14,
        color:colors[Math.floor(Math.random()*colors.length)],round:Math.random()>.72};
      if(burst){
        const ang=Math.random()*Math.PI*2,sp=90+Math.random()*420;
        return {...base,born:Math.random()*220,x:rect.width*burst[0],y:rect.height*burst[1],
          vx:Math.cos(ang)*sp,vy:Math.sin(ang)*sp-160,sway:0,g:430};
      }
      return {...base,born:Math.random()*2600,x:Math.random()*rect.width,y:-12-Math.random()*30,
        vy:90+Math.random()*170,vx:-35+Math.random()*70,sway:10+Math.random()*35,g:22};
    }).sort((a,b)=>a.born-b.born);
    const started=performance.now();
    function draw(now){
      const elapsed=now-started;ctx.clearRect(0,0,rect.width,rect.height);let alive=false;
      for(const p of pieces){
        const age=(elapsed-p.born)/1000;if(age<0){alive=true;continue}
        const y=p.y+p.vy*age+p.g*age*age;if(y<rect.height+30)alive=true;else continue;
        const x=p.x+p.vx*age+Math.sin(age*3+p.phase)*p.sway;
        ctx.save();ctx.translate(x,y);ctx.rotate(p.rotation+p.spin*age);ctx.fillStyle=p.color;
        if(p.round){ctx.beginPath();ctx.arc(0,0,p.size/2,0,Math.PI*2);ctx.fill()}
        else ctx.fillRect(-p.size/2,-p.size/4,p.size,p.size/2);
        ctx.restore();
      }
      if(alive)confettiFrame=requestAnimationFrame(draw);
    }
    confettiFrame=requestAnimationFrame(draw);
  },1000);
}
function activate(slide){
  stopConfetti();
  document.querySelectorAll('.reveal section.run').forEach(s=>s.classList.remove('run'));
  const index=Number(slide?.dataset.caption||0);
  captionText.textContent=slides[index]?.n||'';
  number.textContent=`${index+1} / ${slides.length}`;
  setOceanScene(slide?.dataset.ocean||null);
  document.querySelector('meta[name="theme-color"]').content=slide?.classList.contains('paper')?'#f0eee6':'#261f1a';
  if(slide){
    const bg=getComputedStyle(slide).backgroundColor;
    document.body.style.setProperty('background',bg==='rgba(0, 0, 0, 0)'?'var(--brown-deep)':bg,'important');
  }
  requestAnimationFrame(()=>setTimeout(()=>{slide?.classList.add('run');startConfetti(slide)},90));
}
function toggleCaptions(){
  captionsVisible=!captionsVisible;
  captionBox.classList.toggle('hidden',!captionsVisible);
  toggle.setAttribute('aria-pressed',String(captionsVisible));
}
toggle.addEventListener('click',toggleCaptions);
document.addEventListener('keydown',e=>{if(e.key.toLowerCase()==='c'&&!/input|textarea/i.test(e.target.tagName)){e.preventDefault();e.stopImmediatePropagation();toggleCaptions()}},true);
const demoVideo=document.querySelector('.demo-video');
const demoBadge=document.querySelector('.demo-badge');
demoVideo?.addEventListener('ended',()=>demoBadge?.classList.add('show'));
demoVideo?.addEventListener('play',()=>demoBadge?.classList.remove('show'));
Reveal.on('ready',e=>activate(e.currentSlide));
Reveal.on('slidechanged',e=>activate(e.currentSlide));
